---
title: "AfricaNLP2022 Workshop Schedule"  # Add a page title.
summary: "Overview of our 2-day schedule"  # Add a page description.
#date: "2019-01-01T00:00:00Z"  # Add today's date.
---

+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| **Time (GMT+1)**       | <center>                                                                                                                      |
|                        |                                                                                                                               |
|                        | What?                                                                                                                         |
+:======================:+:=============================================================================================================================:+
| 10:00 - 10:05          | Opening Remark                                                                                                                |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 10:00 - 10:50\         | **Convenience, Random or Purposive Sampling African Languages and Global NLP- - Túndé Adégbọlá**                              |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 11:00          | Q&A for Morning Keynote                                                                                                       |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 11:00 - 11:30          | **Invited Talk: Low-resource natural language processing - Cristina España-Bonet**                                            |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 11:30 - 11:45          | Q&A for Invited Talk                                                                                                          |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 11:45 - 11:55          | Spotlight Talk 1 : Analysing the effects of transfer learning on low-resourced named entity recognition performance           |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 11:55 - 12:05          | Spotlight Talk 2 : Building Text and Speech Datasets for Low Resourced Languages: A Case of Languages in East Africa          |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 12:50 - 12:50          | **Poster Section (Gather Town)**                                                                                              |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 12:50 - 1:30           | **Social + Break** (Break)                                                                                                    |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| **Afternoon Sessions** |                                                                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 1:30 - 2:15            | **Afternoon Keynote - Joyce Nakatumba-Nabende**                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 2:15 - 2:30            | Q&A for Afternoon Keynote (Q&A)                                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 2:30 - 2:40            | Spotlight Talk 3 : Participatory Translations of Oshiwambo: Towards Sustainable Culture Preservation with Language Technology |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
|                        |                                                                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 2:50 - 2:30            | Break                                                                                                                         |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 3:00 - 3:45            | **Poster Section + Social (Gather Town)**                                                                                     |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 3:45 - 4:45            | Panel: Abeba Birhane, Mona Diab, and Audace Niyonkuru - Moderated by Perez Ogayo (discussion panel)                           |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 4:450 - 5:00           | Break                                                                                                                         |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 5:00 - 5:45            | **Invited Talk - Timnit Gebru**                                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
|                        |                                                                                                                               |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 5:45 - 6:00            | Q&A for Invited Talk (Q&A)                                                                                                    |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 6:00 - 7:00            | **Tutorial and Q&A: Zero-resource speech technology with wav2vec - Michael Auli** (invited talk)                              |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 7:00 - 7:25            | **Invited Talk and Q&A: Measuring the Representativeness of NLP Datasets - Antonios Anastasopoulos** (invited talk)           |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 7:25 - 7:30            | Closing remarks - David Adelani (closing remark)                                                                              |
+------------------------+-------------------------------------------------------------------------------------------------------------------------------+
